server:
  port: 8080
spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:scripts/init.sql
  application:
    name: "franchise-ms"
  devtools:
    add-properties: false
  webflux:
    charset: UTF-8
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/franchise_test"
    username: "${MYSQL_USER:root}"
    password: "${MYSQL_PASSWORD:root}"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.MySQLDialect"
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.hibernate: ERROR
    org.hibernate.orm.connections.pooling: ERROR
    com.zaxxer.hikari: ERROR
    org.hibernate.engine.jdbc.env.internal: ERROR
