version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: franchise-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: franchise_test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  franchise-service:
    build:
      context: ../franchises-ms
      dockerfile: deployment/Dockerfile
    container_name: franchise-container
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data: